# This file was created by the group as a whole. 

version: '3.8'

services:
  ml-app:
    build:
      context: .
      dockerfile: Dockerfile.mlapp
    ports:
      - "5001:5000"
    depends_on:
      - mlflow
    networks:
      - ml-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./logs:/app/logs  # Persistent logging

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5002:5000"
    networks:
      - ml-network
    volumes:
      - ./mlruns:/mlflow/mlruns  # Persist MLflow runs

networks:
  ml-network:
    driver: bridge