# This file was compiled by Deepkanwal Singh and Anmol Walia

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /mlflow

# Install MLflow and dependencies
RUN pip install --no-cache-dir mlflow pymysql

# Expose the MLflow UI port
EXPOSE 5000

# Run MLflow tracking server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db"]
