# This file was created by the group as a whole. 

version: '3.8'

services:
  ml-app:
    build:
      context: .
      dockerfile: Dockerfile.mlapp
    ports:
      - "5001:5000"
      - "8002:8002"  # expose LR monitor
      - "8003:8003"  # expose RF monitor
    depends_on:
      - mlflow
    networks:
      - ml-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./logs:/app/logs

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5002:5000"
    networks:
      - ml-network
    volumes:
      - ./mlruns:/mlflow/mlruns

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ml-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - ml-network
    depends_on:
      - prometheus

networks:
  ml-network:
    driver: bridge

volumes:
  mlruns:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local