global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'linear-regression-monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['ml-app:8002']
    metrics_path: /metrics
    scheme: http
    scrape_timeout: 3s

  - job_name: 'random-forest-monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['ml-app:8003']
    metrics_path: /metrics
    scheme: http
    scrape_timeout: 3s